# Generated by Django 3.2.16 on 2022-11-29 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_remove_post_excerpt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
    ]
